### ISSUE TITLE
"Error: Unhandled stream error in pipe." generated when using request

### ISSUE THREAD

**Issue by cauburtin** [niegowski/node-pngjs#18]
I'm doing this:

    var fs = require('fs'),
        request = require('request'),
        PNG = require('pngjs').PNG;
    
    
    var png = new PNG(),
        src = request('http://i.imgur.com/Ho20yXs'),
        dst = fs.createWriteStream('out1.png')
        
    png.on('parsed', function() {
      // do nothing on the picture
        
      png.pack().pipe(dst);
    });
    src.pipe(png)

The image is created but I see this error:

    stream.js:94                                                                                                                            
          throw er; // Unhandled stream error in pipe.                                                                                      
                ^                                                                                                                           
    Error: Invalid file signature                                                                                                           
        at Parser._parseSignature (/home/ubuntu/workspace/node_modules/pngjs/lib/parser.js:87:32)                                           
        at ChunkStream._process (/home/ubuntu/workspace/node_modules/pngjs/lib/chunkstream.js:186:23)                                       
        at ChunkStream.write (/home/ubuntu/workspace/node_modules/pngjs/lib/chunkstream.js:74:10)                                           
        at PNG.write (/home/ubuntu/workspace/node_modules/pngjs/lib/png.js:100:18)                                                          
        at Request.ondata (stream.js:51:26)                                                                                                 
        at Request.emit (events.js:95:17)                                                                                                   
        at IncomingMessage.Request.onRequestResponse.strings (/home/ubuntu/workspace/node_modules/request/request.js:1184:12)               
        at IncomingMessage.emit (events.js:95:17)                                                                                           
        at IncomingMessage.stream.pause.paused (_stream_readable.js:765:14)                                                                 
        at IncomingMessage.emit (events.js:92:17)

**Comment by cauburtin** [comment]
It could be that the file requested is a jpg, but the error is not helping

**Comment by liangzeng** [comment]
start https://github.com/liangzeng/png-word

**Comment by jiangyixiu** [comment]
I also encountered this problem, how do you solve the problem

**Comment by akshayseth** [comment]
same :(
