### ISSUE TITLE
"Error: There are some read requests waitng on finished stream" using docs example

### ISSUE THREAD

**Issue by cauburtin** [niegowski/node-pngjs#19]
When doing:

    var fs = require('fs'),
        request = require('request'),
        PNG = require('pngjs').PNG;
    
    
    var src = fs.createReadStream('out1.png'),
        dst = fs.createWriteStream('out2.png')
        
    src.pipe(new PNG())
    .on('parsed', function() {
      // do nothing on the picture
        
      this.pack().pipe(dst);
    });

the output image is created but an error is spawn:

    Error: There are some read requests waitng on finished stream                                                                           
    at ChunkStream._end (/home/ubuntu/workspace/node_modules/pngjs/lib/chunkstream.js:107:13)                                           
    at ChunkStream.end (/home/ubuntu/workspace/node_modules/pngjs/lib/chunkstream.js:94:14)                                             
    at PNG.end (/home/ubuntu/workspace/node_modules/pngjs/lib/png.js:105:18)                                                            
    at ReadStream.onend (_stream_readable.js:502:10)                                                                                    
    at ReadStream.g (events.js:180:16)                                                                                                  
    at ReadStream.emit (events.js:117:20)                                                                                               
    at _stream_readable.js:944:16                                                                                                       
    at process._tickCallback (node.js:442:13)

**Comment by liangzeng** [comment]
start   https://github.com/liangzeng/png-word
